### ISSUE TITLE
post-processing  error 

### ISSUE THREAD

**Issue by mohsenboojari** [petebachant/UNH-RVAT-3D-OpenFOAM#1]
```
--> FOAM Warning :
    From function dlLibraryTable::open(const fileName&, const bool)
    in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 99
    could not load "libincompressibleRASModels.so"

```

--> FOAM Warning :
    From function dlOpen(const fileName&, const bool)
    in file POSIX.C at line 1179
    dlopen error : libincompressibleRASModels.so: cannot open shared object file: No such file or directory

```
```

**Comment by petebachant** [comment]
Is this occurring with OpenFOAM 3 or higher? These case files have only been used up to 2.3.x.

**Comment by mohsenboojari** [comment]
yeah, I faced this Error by using OF 3.0.x .

sorry but i think it has been written in the turbineFoam readme file that it's provided for OF 3 . am I right?

**Comment by petebachant** [comment]
This particular case doesn't use turbinesFoam. That would be https://github.com/petebachant/UNH-RVAT-turbinesFoam.

**Comment by petebachant** [comment]
This case could be converted to run on 3.0.x by following the steps here: http://petebachant.me/updating-openfoam-case-files-for-30x/.
