### ISSUE TITLE
Gridded vector data

### ISSUE THREAD

**Issue by ahstevens** [petebachant/UNH-RVAT-3D-OpenFOAM#5]
Hi Pete,

I used your figshare download script to get most of the case result files. Can you tell me whether or not one of the outputs is a 3D/4D gridded vector field, or if there is a way to generate that type of data using the case files?

Many thanks!
Drew

**Comment by petebachant** [comment]
Hey Drew,

The data has been stored in OpenFOAM format, where the mesh lives in `constant/polyMesh`, and the fields (and dynamic mesh) live in the numbered directories, where the numbers correspond to times. If you install OpenFOAM, there are a bunch of different data conversion tools available if you have a preferred format, e.g., VTK. Note that there is an OpenFOAM case reader for ParaView so you can do interactive post-processing. Let me know if you have any further questions!

Pete

**Comment by ahstevens** [comment]
Thanks for the quick reply! That clears up a lot of the initial confusion I had about the structure and format of the files. I think I should be able to wrangle them from here, but if I run into anything unexpected I'll ping you.

Cheers,
Drew
